# Generated by Django 2.2.28 on 2024-03-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0002_genre_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='artistName',
            field=models.CharField(blank=True, help_text='Only required if creating an Artist Account', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isArtist',
            field=models.BooleanField(default=True),
        ),
    ]
