# Generated by Django 2.2.28 on 2024-03-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0003_auto_20240319_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
