# Generated by Django 2.2.28 on 2024-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0004_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isMature',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='isArtist',
            field=models.BooleanField(default=False),
        ),
    ]
