# Generated by Django 2.2.28 on 2024-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0008_auto_20240320_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
