# Generated by Django 2.2.28 on 2024-03-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0010_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
