# Generated by Django 2.2.28 on 2024-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0011_remove_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isExplicit',
            field=models.BooleanField(default=False),
        ),
    ]
