# Generated by Django 2.2.28 on 2024-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVapp', '0012_song_isexplicit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isMature',
            field=models.BooleanField(default=False),
        ),
    ]
