# Generated by Django 2.2.28 on 2024-03-22 01:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('MVapp', '0014_auto_20240320_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
